<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FontAwesome.Sharp" Version="6.6.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="CicloFor.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="CicloFor.Designer.cs">
      <DependentUpon>CicloFor.cs</DependentUpon>
    </Compile>
    <Compile Update="MenuTemaFor.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="MenuTemaFor.Designer.cs">
      <DependentUpon>MenuTemaFor.cs</DependentUpon>
    </Compile>
    <Compile Update="MenuTemaDoWhile.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="MenuTemaDoWhile.Designer.cs">
      <DependentUpon>MenuTemaDoWhile.cs</DependentUpon>
    </Compile>
    <Compile Update="Menuvariables.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Menuvariables.Designer.cs">
      <DependentUpon>Menuvariables.cs</DependentUpon>
    </Compile>
    <Compile Update="FrmVariables.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="FrmVariables.Designer.cs">
      <DependentUpon>FrmVariables.cs</DependentUpon>
    </Compile>
    <Compile Update="FrmDeclaracionVariables.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="FrmDeclaracionVariables.Designer.cs">
      <DependentUpon>FrmDeclaracionVariables.cs</DependentUpon>
    </Compile>
    <Compile Update="DashboardPrincipal.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="DashboardPrincipal.Designer.cs">
      <DependentUpon>DashboardPrincipal.cs</DependentUpon>
    </Compile>
    <Compile Update="MenuJuegos.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="MenuJuegos.Designer.cs">
      <DependentUpon>MenuJuegos.cs</DependentUpon>
    </Compile>
    <Compile Update="MinijuegoOrdenarCodigo.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="MinijuegoOrdenarCodigo.Designer.cs">
      <DependentUpon>MinijuegoOrdenarCodigo.cs</DependentUpon>
    </Compile>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="CicloFor.resx">
      <DependentUpon>CicloFor.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="MenuTemaFor.resx">
      <DependentUpon>MenuTemaFor.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="MenuTemaDoWhile.resx">
      <DependentUpon>MenuTemaDoWhile.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="Menuvariables.resx">
      <DependentUpon>Menuvariables.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="FrmVariables.resx">
      <DependentUpon>FrmVariables.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="FrmDeclaracionVariables.resx">
      <DependentUpon>FrmDeclaracionVariables.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="DashboardPrincipal.resx">
      <DependentUpon>DashboardPrincipal.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="MenuJuegos.resx">
      <DependentUpon>MenuJuegos.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="MinijuegoOrdenarCodigo.resx">
      <DependentUpon>MinijuegoOrdenarCodigo.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>